export const FETCH_USERS_SAGA = "FETCH_USERS_SAGA";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const FETCH_USER_DETAIL_SAGA = "FETCH_USER_DETAIL_SAGA";
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS";
export const FETCH_USER_DETAIL_ERROR = "FETCH_USER_DETAIL_ERROR";

export const FETCH_CATEGORIES_SAGA = "FETCH_CATEGORIES_SAGA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";

export const FETCH_SOURCES_SAGA = "FETCH_SOURCES_SAGA";
export const FETCH_SOURCES_SUCCESS = "FETCH_SOURCES_SUCCESS";
export const FETCH_SOURCES_ERROR = "FETCH_SOURCES_ERROR";

export const FETCH_USERS_SEARCH_SAGA = "FETCH_USERS_SEARCH_SAGA";
export const FETCH_USERS_SEARCH_SUCCESS = "FETCH_USERS_SEARCH_SUCCESS";
export const FETCH_USERS_SEARCH_ERROR = "FETCH_USERS_SEARCH_ERROR";

export const FETCH_CANCEL_FILTER_SAGA = "FETCH_CANCEL_FILTER_SAGA";
