export const FETCH_AUTH_LOGIN_SUCCESS = "FETCH_AUTH_LOGIN_SUCCESS";
export const FETCH_AUTH_LOGIN_ERROR = "FETCH_AUTH_LOGIN_ERROR";
export const FETCH_AUTH_LOGIN_SAGA = "FETCH_AUTH_LOGIN_SAGA";

export const FETCH_AUTH_REGISTER_SUCCESS = "FETCH_AUTH_REGISTER_SUCCESS";
export const FETCH_AUTH_REGISTER_ERROR = "FETCH_AUTH_REGISTER_ERROR";
export const FETCH_AUTH_REGISTER_SAGA = "FETCH_AUTH_REGISTER_SAGA";

export const FETCH_AUTH_LOGOUT_SAGA = "FETCH_AUTH_LOGOUT_SAGA";
export const FETCH_AUTH_LOGOUT = "FETCH_AUTH_LOGOUT";
